import type { Patient, Prescription } from "@/features/patients/types";
import type { Appointment } from "@/features/appointments/types";
import type { BillingRecord } from "@/features/billing/types";
import type { MetricDataPoint, DepartmentStat } from "@/features/analytics/types";

export const mockPatients: Patient[] = [
  {
    id: "P001",
    name: "Aarav Mehta",
    age: 45,
    gender: "Male",
    bloodGroup: "A+",
    status: "Active",
    diagnosis: "Type 2 Diabetes",
    department: "Endocrinology",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2026-04-10",
    lastVisit: "2026-05-08",
    phone: "+91 98201 11234",
    email: "aarav.mehta@email.com",
    address: "12 Marine Lines, Mumbai",
    avatar: "AM",
    vitals: {
      heartRate: 78,
      bloodPressure: "128/82",
      temperature: 98.6,
      oxygenSat: 97,
      weight: 82,
    },
    tags: ["Diabetic", "High BP"],
  },
  {
    id: "P002",
    name: "Sanya Kapoor",
    age: 32,
    gender: "Female",
    bloodGroup: "B+",
    status: "Recovering",
    diagnosis: "Pneumonia",
    department: "Pulmonology",
    doctor: "Dr. Arjun Nair",
    admissionDate: "2026-05-01",
    lastVisit: "2026-05-10",
    phone: "+91 99301 22345",
    email: "sanya.kapoor@email.com",
    address: "45 Koregaon Park, Pune",
    avatar: "SK",
    vitals: {
      heartRate: 88,
      bloodPressure: "118/76",
      temperature: 99.2,
      oxygenSat: 94,
      weight: 58,
    },
    tags: ["Respiratory", "Under Observation"],
  },
  {
    id: "P003",
    name: "Rohan Verma",
    age: 61,
    gender: "Male",
    bloodGroup: "O+",
    status: "Critical",
    diagnosis: "Acute MI",
    department: "Cardiology",
    doctor: "Dr. Sneha Iyer",
    admissionDate: "2026-05-09",
    lastVisit: "2026-05-11",
    phone: "+91 98765 33456",
    email: "rohan.verma@email.com",
    address: "7 Indiranagar, Bangalore",
    avatar: "RV",
    vitals: {
      heartRate: 102,
      bloodPressure: "155/98",
      temperature: 99.8,
      oxygenSat: 91,
      weight: 76,
    },
    tags: ["Cardiac", "ICU", "High Risk"],
  },
  {
    id: "P004",
    name: "Nisha Patel",
    age: 28,
    gender: "Female",
    bloodGroup: "AB+",
    status: "Active",
    diagnosis: "Migraine",
    department: "Neurology",
    doctor: "Dr. Vikram Rao",
    admissionDate: "2026-04-20",
    lastVisit: "2026-05-07",
    phone: "+91 98912 44567",
    email: "nisha.patel@email.com",
    address: "23 Satellite, Ahmedabad",
    avatar: "NP",
    vitals: {
      heartRate: 72,
      bloodPressure: "112/72",
      temperature: 98.4,
      oxygenSat: 99,
      weight: 54,
    },
    tags: ["Neurological"],
  },
  {
    id: "P005",
    name: "Karan Singh",
    age: 53,
    gender: "Male",
    bloodGroup: "A-",
    status: "Active",
    diagnosis: "Hypertension",
    department: "Cardiology",
    doctor: "Dr. Sneha Iyer",
    admissionDate: "2026-03-15",
    lastVisit: "2026-05-05",
    phone: "+91 99881 55678",
    email: "karan.singh@email.com",
    address: "56 Sector 18, Noida",
    avatar: "KS",
    vitals: {
      heartRate: 82,
      bloodPressure: "145/90",
      temperature: 98.6,
      oxygenSat: 96,
      weight: 89,
    },
    tags: ["High BP", "Cardiac Risk"],
  },
  {
    id: "P006",
    name: "Ananya Roy",
    age: 38,
    gender: "Female",
    bloodGroup: "O-",
    status: "Discharged",
    diagnosis: "Appendicitis",
    department: "Surgery",
    doctor: "Dr. Rahul Gupta",
    admissionDate: "2026-04-25",
    lastVisit: "2026-05-02",
    phone: "+91 98234 66789",
    email: "ananya.roy@email.com",
    address: "89 Salt Lake, Kolkata",
    avatar: "AR",
    vitals: {
      heartRate: 70,
      bloodPressure: "110/70",
      temperature: 98.2,
      oxygenSat: 99,
      weight: 62,
    },
    tags: ["Post-Op", "Discharged"],
  },
  {
    id: "P007",
    name: "Vikram Nair",
    age: 47,
    gender: "Male",
    bloodGroup: "B-",
    status: "Active",
    diagnosis: "Chronic Kidney Disease",
    department: "Nephrology",
    doctor: "Dr. Meera Pillai",
    admissionDate: "2026-02-10",
    lastVisit: "2026-05-09",
    phone: "+91 99123 77890",
    email: "vikram.nair@email.com",
    address: "34 Panjim, Goa",
    avatar: "VN",
    vitals: {
      heartRate: 76,
      bloodPressure: "132/84",
      temperature: 98.7,
      oxygenSat: 96,
      weight: 71,
    },
    tags: ["Renal", "Dialysis"],
  },
  {
    id: "P008",
    name: "Priya Sharma",
    age: 25,
    gender: "Female",
    bloodGroup: "A+",
    status: "Recovering",
    diagnosis: "Dengue Fever",
    department: "Internal Medicine",
    doctor: "Dr. Arjun Nair",
    admissionDate: "2026-05-06",
    lastVisit: "2026-05-10",
    phone: "+91 98567 88901",
    email: "priya.sharma@email.com",
    address: "12 Banjara Hills, Hyderabad",
    avatar: "PS",
    vitals: {
      heartRate: 90,
      bloodPressure: "108/68",
      temperature: 101.2,
      oxygenSat: 95,
      weight: 51,
    },
    tags: ["Fever", "Vector-borne"],
  },
  {
    id: "P009",
    name: "Arjun Desai",
    age: 70,
    gender: "Male",
    bloodGroup: "AB-",
    status: "Critical",
    diagnosis: "COPD Exacerbation",
    department: "Pulmonology",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2026-05-08",
    lastVisit: "2026-05-11",
    phone: "+91 99345 99012",
    email: "arjun.desai@email.com",
    address: "67 Navrangpura, Ahmedabad",
    avatar: "AD",
    vitals: {
      heartRate: 98,
      bloodPressure: "140/88",
      temperature: 100.1,
      oxygenSat: 88,
      weight: 65,
    },
    tags: ["Respiratory", "ICU", "Elderly"],
  },
  {
    id: "P010",
    name: "Meera Iyer",
    age: 42,
    gender: "Female",
    bloodGroup: "O+",
    status: "Active",
    diagnosis: "Hypothyroidism",
    department: "Endocrinology",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2026-01-20",
    lastVisit: "2026-05-04",
    phone: "+91 98789 10123",
    email: "meera.iyer@email.com",
    address: "23 Anna Nagar, Chennai",
    avatar: "MI",
    vitals: {
      heartRate: 68,
      bloodPressure: "118/78",
      temperature: 97.8,
      oxygenSat: 98,
      weight: 67,
    },
    tags: ["Thyroid", "Hormonal"],
  },
  {
    id: "P011",
    name: "Rahul Bose",
    age: 35,
    gender: "Male",
    bloodGroup: "B+",
    status: "Active",
    diagnosis: "Lower Back Pain",
    department: "Orthopedics",
    doctor: "Dr. Vikram Rao",
    admissionDate: "2026-04-30",
    lastVisit: "2026-05-06",
    phone: "+91 99567 21234",
    email: "rahul.bose@email.com",
    address: "45 Park Street, Kolkata",
    avatar: "RB",
    vitals: {
      heartRate: 74,
      bloodPressure: "120/80",
      temperature: 98.4,
      oxygenSat: 99,
      weight: 78,
    },
    tags: ["Musculoskeletal"],
  },
  {
    id: "P012",
    name: "Divya Menon",
    age: 29,
    gender: "Female",
    bloodGroup: "A+",
    status: "Recovering",
    diagnosis: "Gallstones",
    department: "Surgery",
    doctor: "Dr. Rahul Gupta",
    admissionDate: "2026-05-03",
    lastVisit: "2026-05-09",
    phone: "+91 98901 32345",
    email: "divya.menon@email.com",
    address: "78 Thrissur, Kerala",
    avatar: "DM",
    vitals: {
      heartRate: 80,
      bloodPressure: "114/74",
      temperature: 98.8,
      oxygenSat: 97,
      weight: 55,
    },
    tags: ["Post-Op", "Digestive"],
  },
  {
    id: "P013",
    name: "Suresh Kumar",
    age: 58,
    gender: "Male",
    bloodGroup: "O+",
    status: "Active",
    diagnosis: "Osteoarthritis",
    department: "Orthopedics",
    doctor: "Dr. Meera Pillai",
    admissionDate: "2026-03-01",
    lastVisit: "2026-05-03",
    phone: "+91 99012 43456",
    email: "suresh.kumar@email.com",
    address: "12 Mysore Road, Bangalore",
    avatar: "SK",
    vitals: {
      heartRate: 72,
      bloodPressure: "130/82",
      temperature: 98.5,
      oxygenSat: 97,
      weight: 84,
    },
    tags: ["Joint Pain", "Elderly"],
  },
  {
    id: "P014",
    name: "Kavitha Rajan",
    age: 44,
    gender: "Female",
    bloodGroup: "B+",
    status: "Active",
    diagnosis: "Fibromyalgia",
    department: "Rheumatology",
    doctor: "Dr. Sneha Iyer",
    admissionDate: "2026-02-14",
    lastVisit: "2026-05-01",
    phone: "+91 98234 54567",
    email: "kavitha.rajan@email.com",
    address: "34 RA Puram, Chennai",
    avatar: "KR",
    vitals: {
      heartRate: 76,
      bloodPressure: "116/76",
      temperature: 98.6,
      oxygenSat: 98,
      weight: 61,
    },
    tags: ["Chronic Pain", "Autoimmune"],
  },
  {
    id: "P015",
    name: "Aditya Shah",
    age: 22,
    gender: "Male",
    bloodGroup: "AB+",
    status: "Discharged",
    diagnosis: "Fracture - Right Arm",
    department: "Orthopedics",
    doctor: "Dr. Rahul Gupta",
    admissionDate: "2026-04-15",
    lastVisit: "2026-04-28",
    phone: "+91 99678 65678",
    email: "aditya.shah@email.com",
    address: "56 Borivali, Mumbai",
    avatar: "AS",
    vitals: {
      heartRate: 68,
      bloodPressure: "110/70",
      temperature: 98.2,
      oxygenSat: 99,
      weight: 70,
    },
    tags: ["Trauma", "Discharged"],
  },
  {
    id: "P016",
    name: "Lakshmi Naidu",
    age: 66,
    gender: "Female",
    bloodGroup: "A-",
    status: "Critical",
    diagnosis: "Stroke",
    department: "Neurology",
    doctor: "Dr. Vikram Rao",
    admissionDate: "2026-05-10",
    lastVisit: "2026-05-11",
    phone: "+91 98456 76789",
    email: "lakshmi.naidu@email.com",
    address: "89 Vijayawada, AP",
    avatar: "LN",
    vitals: {
      heartRate: 96,
      bloodPressure: "168/102",
      temperature: 100.4,
      oxygenSat: 92,
      weight: 58,
    },
    tags: ["Neurological", "ICU", "High Risk"],
  },
  {
    id: "P017",
    name: "Rohit Sharma",
    age: 40,
    gender: "Male",
    bloodGroup: "O+",
    status: "Active",
    diagnosis: "Asthma",
    department: "Pulmonology",
    doctor: "Dr. Arjun Nair",
    admissionDate: "2026-03-20",
    lastVisit: "2026-05-07",
    phone: "+91 99890 87890",
    email: "rohit.sharma@email.com",
    address: "23 Dwarka, Delhi",
    avatar: "RS",
    vitals: {
      heartRate: 80,
      bloodPressure: "122/78",
      temperature: 98.6,
      oxygenSat: 95,
      weight: 73,
    },
    tags: ["Respiratory", "Allergic"],
  },
  {
    id: "P018",
    name: "Pooja Tiwari",
    age: 31,
    gender: "Female",
    bloodGroup: "B-",
    status: "Active",
    diagnosis: "Anemia",
    department: "Internal Medicine",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2026-04-05",
    lastVisit: "2026-05-08",
    phone: "+91 98123 98901",
    email: "pooja.tiwari@email.com",
    address: "67 Hazratganj, Lucknow",
    avatar: "PT",
    vitals: {
      heartRate: 92,
      bloodPressure: "105/65",
      temperature: 98.0,
      oxygenSat: 96,
      weight: 48,
    },
    tags: ["Hematology", "Iron Deficiency"],
  },
  {
    id: "P019",
    name: "Gaurav Joshi",
    age: 50,
    gender: "Male",
    bloodGroup: "A+",
    status: "Recovering",
    diagnosis: "Hepatitis B",
    department: "Gastroenterology",
    doctor: "Dr. Meera Pillai",
    admissionDate: "2026-04-22",
    lastVisit: "2026-05-09",
    phone: "+91 99234 09012",
    email: "gaurav.joshi@email.com",
    address: "34 Shivaji Nagar, Pune",
    avatar: "GJ",
    vitals: {
      heartRate: 78,
      bloodPressure: "124/80",
      temperature: 99.0,
      oxygenSat: 96,
      weight: 75,
    },
    tags: ["Liver", "Infectious"],
  },
  {
    id: "P020",
    name: "Sunita Agarwal",
    age: 55,
    gender: "Female",
    bloodGroup: "O-",
    status: "Active",
    diagnosis: "Type 1 Diabetes",
    department: "Endocrinology",
    doctor: "Dr. Priya Sharma",
    admissionDate: "2026-01-10",
    lastVisit: "2026-05-06",
    phone: "+91 98789 10234",
    email: "sunita.agarwal@email.com",
    address: "12 Civil Lines, Jaipur",
    avatar: "SA",
    vitals: {
      heartRate: 74,
      bloodPressure: "120/78",
      temperature: 98.4,
      oxygenSat: 97,
      weight: 63,
    },
    tags: ["Diabetic", "Insulin Dependent"],
  },
];

export const metricsData: MetricDataPoint[] = [
  { month: "Nov", patients: 310, revenue: 420000, appointments: 280, recovered: 185 },
  { month: "Dec", patients: 340, revenue: 460000, appointments: 310, recovered: 210 },
  { month: "Jan", patients: 290, revenue: 390000, appointments: 265, recovered: 178 },
  { month: "Feb", patients: 370, revenue: 510000, appointments: 340, recovered: 240 },
  { month: "Mar", patients: 420, revenue: 580000, appointments: 390, recovered: 275 },
  { month: "Apr", patients: 395, revenue: 545000, appointments: 360, recovered: 258 },
  { month: "May", patients: 450, revenue: 620000, appointments: 415, recovered: 298 },
];

export const mockBillingData: BillingRecord[] = [
  {
    id: "B001",
    patientId: "P001",
    patientName: "Aarav Mehta",
    patientAvatar: "AM",
    visitDate: "2026-05-08",
    department: "Endocrinology",
    procedure: "Diabetes Management & HbA1c Panel",
    doctor: "Dr. Priya Sharma",
    totalAmount: 8500,
    insuranceProvider: "Star Health Insurance",
    policyNumber: "SH-2024-00112",
    claimStatus: "Approved",
    insuranceCovered: 6800,
    patientDue: 1700,
  },
  {
    id: "B002",
    patientId: "P002",
    patientName: "Sanya Kapoor",
    patientAvatar: "SK",
    visitDate: "2026-05-10",
    department: "Pulmonology",
    procedure: "Pneumonia Treatment — 9 day admission",
    doctor: "Dr. Arjun Nair",
    totalAmount: 45000,
    insuranceProvider: "HDFC ERGO Health",
    policyNumber: "HE-2023-88321",
    claimStatus: "Approved",
    insuranceCovered: 38250,
    patientDue: 6750,
  },
  {
    id: "B003",
    patientId: "P003",
    patientName: "Rohan Verma",
    patientAvatar: "RV",
    visitDate: "2026-05-09",
    department: "Cardiology",
    procedure: "Cardiac Catheterization + ICU Stay",
    doctor: "Dr. Sneha Iyer",
    totalAmount: 185000,
    insuranceProvider: "Bajaj Allianz Health",
    policyNumber: "BA-2024-55043",
    claimStatus: "Pending",
    insuranceCovered: 0,
    patientDue: 185000,
  },
  {
    id: "B004",
    patientId: "P004",
    patientName: "Nisha Patel",
    patientAvatar: "NP",
    visitDate: "2026-05-07",
    department: "Neurology",
    procedure: "MRI Brain + Neurologist Consultation",
    doctor: "Dr. Vikram Rao",
    totalAmount: 12000,
    insuranceProvider: "Niva Bupa Health",
    policyNumber: "NB-2025-19874",
    claimStatus: "Approved",
    insuranceCovered: 9600,
    patientDue: 2400,
  },
  {
    id: "B005",
    patientId: "P005",
    patientName: "Karan Singh",
    patientAvatar: "KS",
    visitDate: "2026-05-05",
    department: "Cardiology",
    procedure: "ECG, Holter Monitor & Cardiology OPD",
    doctor: "Dr. Sneha Iyer",
    totalAmount: 6500,
    insuranceProvider: "New India Assurance",
    policyNumber: "NIA-2022-30091",
    claimStatus: "Denied",
    insuranceCovered: 0,
    patientDue: 6500,
  },
  {
    id: "B006",
    patientId: "P006",
    patientName: "Ananya Roy",
    patientAvatar: "AR",
    visitDate: "2026-05-02",
    department: "Surgery",
    procedure: "Laparoscopic Appendectomy",
    doctor: "Dr. Rahul Gupta",
    totalAmount: 75000,
    insuranceProvider: "ICICI Lombard Health",
    policyNumber: "IL-2024-72210",
    claimStatus: "Approved",
    insuranceCovered: 67500,
    patientDue: 7500,
  },
  {
    id: "B007",
    patientId: "P007",
    patientName: "Vikram Nair",
    patientAvatar: "VN",
    visitDate: "2026-05-09",
    department: "Nephrology",
    procedure: "Haemodialysis × 4 Sessions",
    doctor: "Dr. Meera Pillai",
    totalAmount: 28000,
    insuranceProvider: "Star Health Insurance",
    policyNumber: "SH-2023-44556",
    claimStatus: "Partial",
    insuranceCovered: 14000,
    patientDue: 14000,
  },
  {
    id: "B008",
    patientId: "P008",
    patientName: "Priya Sharma",
    patientAvatar: "PS",
    visitDate: "2026-05-10",
    department: "Internal Medicine",
    procedure: "Dengue IV Therapy — 5 day admission",
    doctor: "Dr. Arjun Nair",
    totalAmount: 32000,
    insuranceProvider: "HDFC ERGO Health",
    policyNumber: "HE-2025-10034",
    claimStatus: "Approved",
    insuranceCovered: 28800,
    patientDue: 3200,
  },
  {
    id: "B009",
    patientId: "P009",
    patientName: "Arjun Desai",
    patientAvatar: "AD",
    visitDate: "2026-05-11",
    department: "Pulmonology",
    procedure: "ICU Stay + Mechanical Ventilation",
    doctor: "Dr. Priya Sharma",
    totalAmount: 220000,
    insuranceProvider: "Bajaj Allianz Health",
    policyNumber: "BA-2023-98712",
    claimStatus: "Pending",
    insuranceCovered: 0,
    patientDue: 220000,
  },
  {
    id: "B010",
    patientId: "P010",
    patientName: "Meera Iyer",
    patientAvatar: "MI",
    visitDate: "2026-05-04",
    department: "Endocrinology",
    procedure: "Thyroid Panel, Ultrasound & Medication",
    doctor: "Dr. Priya Sharma",
    totalAmount: 9500,
    insuranceProvider: "United India Insurance",
    policyNumber: "UI-2022-66123",
    claimStatus: "Denied",
    insuranceCovered: 0,
    patientDue: 9500,
  },
  {
    id: "B011",
    patientId: "P011",
    patientName: "Rahul Bose",
    patientAvatar: "RB",
    visitDate: "2026-05-06",
    department: "Orthopedics",
    procedure: "Physiotherapy & Spinal Evaluation × 6",
    doctor: "Dr. Vikram Rao",
    totalAmount: 18000,
    insuranceProvider: "Niva Bupa Health",
    policyNumber: "NB-2024-33421",
    claimStatus: "Approved",
    insuranceCovered: 14400,
    patientDue: 3600,
  },
  {
    id: "B012",
    patientId: "P012",
    patientName: "Divya Menon",
    patientAvatar: "DM",
    visitDate: "2026-05-09",
    department: "Surgery",
    procedure: "Laparoscopic Cholecystectomy",
    doctor: "Dr. Rahul Gupta",
    totalAmount: 95000,
    insuranceProvider: "ICICI Lombard Health",
    policyNumber: "IL-2025-81009",
    claimStatus: "Approved",
    insuranceCovered: 80750,
    patientDue: 14250,
  },
  {
    id: "B013",
    patientId: "P013",
    patientName: "Suresh Kumar",
    patientAvatar: "SK",
    visitDate: "2026-05-03",
    department: "Orthopedics",
    procedure: "Partial Knee Replacement Surgery",
    doctor: "Dr. Meera Pillai",
    totalAmount: 145000,
    insuranceProvider: "New India Assurance",
    policyNumber: "NIA-2024-47832",
    claimStatus: "Partial",
    insuranceCovered: 87000,
    patientDue: 58000,
  },
  {
    id: "B014",
    patientId: "P016",
    patientName: "Lakshmi Naidu",
    patientAvatar: "LN",
    visitDate: "2026-05-10",
    department: "Neurology",
    procedure: "Stroke Emergency & Neuro ICU",
    doctor: "Dr. Vikram Rao",
    totalAmount: 280000,
    insuranceProvider: "Star Health Insurance",
    policyNumber: "SH-2025-02341",
    claimStatus: "Pending",
    insuranceCovered: 0,
    patientDue: 280000,
  },
  {
    id: "B015",
    patientId: "P017",
    patientName: "Rohit Sharma",
    patientAvatar: "RS",
    visitDate: "2026-05-07",
    department: "Pulmonology",
    procedure: "Pulmonary Function Test & Spirometry",
    doctor: "Dr. Arjun Nair",
    totalAmount: 7500,
    insuranceProvider: "HDFC ERGO Health",
    policyNumber: "HE-2024-56678",
    claimStatus: "Approved",
    insuranceCovered: 6000,
    patientDue: 1500,
  },
  {
    id: "B016",
    patientId: "P019",
    patientName: "Gaurav Joshi",
    patientAvatar: "GJ",
    visitDate: "2026-05-09",
    department: "Gastroenterology",
    procedure: "Hepatitis B Antiviral Therapy — 18 days",
    doctor: "Dr. Meera Pillai",
    totalAmount: 55000,
    insuranceProvider: "Bajaj Allianz Health",
    policyNumber: "BA-2025-11234",
    claimStatus: "Approved",
    insuranceCovered: 46750,
    patientDue: 8250,
  },
  {
    id: "B017",
    patientId: "P020",
    patientName: "Sunita Agarwal",
    patientAvatar: "SA",
    visitDate: "2026-05-06",
    department: "Endocrinology",
    procedure: "Insulin Pump Setup & Diabetic Counselling",
    doctor: "Dr. Priya Sharma",
    totalAmount: 35000,
    insuranceProvider: "United India Insurance",
    policyNumber: "UI-2024-29901",
    claimStatus: "Partial",
    insuranceCovered: 21000,
    patientDue: 14000,
  },
];

export const todayAppointmentCount = 8;

export const mockPrescriptions: Prescription[] = [
  {
    id: "RX001",
    patientId: "P001",
    medication: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    duration: "90 days",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-04-10",
    status: "Active",
    refillsLeft: 2,
  },
  {
    id: "RX002",
    patientId: "P001",
    medication: "Glipizide",
    dosage: "5mg",
    frequency: "Once daily (morning)",
    duration: "60 days",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-04-10",
    status: "Active",
    refillsLeft: 1,
  },
  {
    id: "RX003",
    patientId: "P001",
    medication: "Lisinopril",
    dosage: "10mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-04-10",
    status: "Active",
    refillsLeft: 2,
    notes: "Monitor BP weekly",
  },
  {
    id: "RX004",
    patientId: "P002",
    medication: "Amoxicillin",
    dosage: "500mg",
    frequency: "Three times daily",
    duration: "7 days",
    prescribedBy: "Dr. Arjun Nair",
    prescribedDate: "2026-05-01",
    status: "Active",
    refillsLeft: 0,
  },
  {
    id: "RX005",
    patientId: "P002",
    medication: "Azithromycin",
    dosage: "250mg",
    frequency: "Once daily",
    duration: "5 days",
    prescribedBy: "Dr. Arjun Nair",
    prescribedDate: "2026-04-28",
    status: "Completed",
    refillsLeft: 0,
  },
  {
    id: "RX006",
    patientId: "P003",
    medication: "Aspirin",
    dosage: "75mg",
    frequency: "Once daily",
    duration: "Ongoing",
    prescribedBy: "Dr. Sneha Iyer",
    prescribedDate: "2026-05-09",
    status: "Active",
    refillsLeft: 3,
  },
  {
    id: "RX007",
    patientId: "P003",
    medication: "Atorvastatin",
    dosage: "40mg",
    frequency: "Once daily (night)",
    duration: "90 days",
    prescribedBy: "Dr. Sneha Iyer",
    prescribedDate: "2026-05-09",
    status: "Active",
    refillsLeft: 2,
  },
  {
    id: "RX008",
    patientId: "P003",
    medication: "Metoprolol",
    dosage: "25mg",
    frequency: "Twice daily",
    duration: "30 days",
    prescribedBy: "Dr. Sneha Iyer",
    prescribedDate: "2026-05-09",
    status: "Active",
    refillsLeft: 1,
    notes: "Do not stop abruptly",
  },
  {
    id: "RX009",
    patientId: "P004",
    medication: "Sumatriptan",
    dosage: "50mg",
    frequency: "As needed",
    duration: "10 tablets",
    prescribedBy: "Dr. Vikram Rao",
    prescribedDate: "2026-04-20",
    status: "Active",
    refillsLeft: 1,
  },
  {
    id: "RX010",
    patientId: "P004",
    medication: "Propranolol",
    dosage: "40mg",
    frequency: "Once daily",
    duration: "30 days",
    prescribedBy: "Dr. Vikram Rao",
    prescribedDate: "2026-04-20",
    status: "Active",
    refillsLeft: 1,
  },
  {
    id: "RX011",
    patientId: "P005",
    medication: "Amlodipine",
    dosage: "5mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Sneha Iyer",
    prescribedDate: "2026-03-15",
    status: "Active",
    refillsLeft: 2,
  },
  {
    id: "RX012",
    patientId: "P005",
    medication: "Telmisartan",
    dosage: "40mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Sneha Iyer",
    prescribedDate: "2026-03-15",
    status: "Active",
    refillsLeft: 2,
    notes: "Take on empty stomach",
  },
  {
    id: "RX013",
    patientId: "P007",
    medication: "Erythropoietin",
    dosage: "4000 IU",
    frequency: "Thrice weekly",
    duration: "30 days",
    prescribedBy: "Dr. Meera Pillai",
    prescribedDate: "2026-05-09",
    status: "Active",
    refillsLeft: 1,
    notes: "SC injection",
  },
  {
    id: "RX014",
    patientId: "P007",
    medication: "Calcium Carbonate",
    dosage: "500mg",
    frequency: "Three times daily with meals",
    duration: "90 days",
    prescribedBy: "Dr. Meera Pillai",
    prescribedDate: "2026-05-09",
    status: "Active",
    refillsLeft: 2,
  },
  {
    id: "RX015",
    patientId: "P008",
    medication: "Paracetamol",
    dosage: "500mg",
    frequency: "Four times daily",
    duration: "5 days",
    prescribedBy: "Dr. Arjun Nair",
    prescribedDate: "2026-05-06",
    status: "Completed",
    refillsLeft: 0,
  },
  {
    id: "RX016",
    patientId: "P009",
    medication: "Tiotropium",
    dosage: "18mcg",
    frequency: "Once daily (inhaler)",
    duration: "30 days",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-05-08",
    status: "Active",
    refillsLeft: 1,
  },
  {
    id: "RX017",
    patientId: "P009",
    medication: "Prednisolone",
    dosage: "30mg",
    frequency: "Once daily (morning)",
    duration: "5 days",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-05-08",
    status: "Active",
    refillsLeft: 0,
    notes: "Taper dose after 5 days",
  },
  {
    id: "RX018",
    patientId: "P009",
    medication: "Salbutamol",
    dosage: "100mcg",
    frequency: "As needed (inhaler)",
    duration: "1 month",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-05-08",
    status: "Active",
    refillsLeft: 2,
  },
  {
    id: "RX019",
    patientId: "P010",
    medication: "Levothyroxine",
    dosage: "50mcg",
    frequency: "Once daily (empty stomach)",
    duration: "90 days",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-01-20",
    status: "Active",
    refillsLeft: 3,
    notes: "Take 30 min before breakfast",
  },
  {
    id: "RX020",
    patientId: "P016",
    medication: "Clopidogrel",
    dosage: "75mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Vikram Rao",
    prescribedDate: "2026-05-10",
    status: "Active",
    refillsLeft: 2,
  },
  {
    id: "RX021",
    patientId: "P016",
    medication: "Atorvastatin",
    dosage: "80mg",
    frequency: "Once daily (night)",
    duration: "90 days",
    prescribedBy: "Dr. Vikram Rao",
    prescribedDate: "2026-05-10",
    status: "Active",
    refillsLeft: 2,
  },
  {
    id: "RX022",
    patientId: "P016",
    medication: "Ramipril",
    dosage: "2.5mg",
    frequency: "Once daily",
    duration: "30 days",
    prescribedBy: "Dr. Vikram Rao",
    prescribedDate: "2026-05-10",
    status: "Active",
    refillsLeft: 1,
    notes: "Titrate up based on BP",
  },
  {
    id: "RX023",
    patientId: "P019",
    medication: "Tenofovir",
    dosage: "300mg",
    frequency: "Once daily with food",
    duration: "180 days",
    prescribedBy: "Dr. Meera Pillai",
    prescribedDate: "2026-04-22",
    status: "Active",
    refillsLeft: 3,
  },
  {
    id: "RX024",
    patientId: "P019",
    medication: "Vitamin D3",
    dosage: "60,000 IU",
    frequency: "Once weekly",
    duration: "8 weeks",
    prescribedBy: "Dr. Meera Pillai",
    prescribedDate: "2026-04-22",
    status: "Active",
    refillsLeft: 0,
  },
  {
    id: "RX025",
    patientId: "P020",
    medication: "Insulin Glargine",
    dosage: "20 units",
    frequency: "Once daily (bedtime)",
    duration: "90 days",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-01-10",
    status: "Active",
    refillsLeft: 2,
    notes: "Adjust dose per CGM readings",
  },
  {
    id: "RX026",
    patientId: "P020",
    medication: "Insulin Aspart",
    dosage: "6 units",
    frequency: "Before each meal",
    duration: "90 days",
    prescribedBy: "Dr. Priya Sharma",
    prescribedDate: "2026-01-10",
    status: "Active",
    refillsLeft: 2,
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "A001",
    patientId: "P001",
    patientName: "Aarav Mehta",
    patientAvatar: "AM",
    dob: "15 Mar 1981",
    phone: "+91 98201 11234",
    doctor: "Dr. Priya Sharma",
    department: "Endocrinology",
    clinicName: "Diabetes & Endocrine Clinic",
    date: "2026-05-11",
    time: "09:00",
    duration: 30,
    status: "Confirmed",
    type: "Follow-up",
    intakeComplete: true,
    insuranceVerified: true,
    insuranceProvider: "Star Health Insurance",
  },
  {
    id: "A002",
    patientId: "P003",
    patientName: "Rohan Verma",
    patientAvatar: "RV",
    dob: "22 Jan 1965",
    phone: "+91 98765 33456",
    doctor: "Dr. Sneha Iyer",
    department: "Cardiology",
    clinicName: "Cardiac Centre, Floor 3",
    date: "2026-05-11",
    time: "09:30",
    duration: 60,
    status: "Confirmed",
    type: "Emergency",
    notes: "Critical — ICU follow-up post cardiac catheterization",
    intakeComplete: true,
    insuranceVerified: false,
    insuranceProvider: "Bajaj Allianz Health",
  },
  {
    id: "A003",
    patientId: "P004",
    patientName: "Nisha Patel",
    patientAvatar: "NP",
    dob: "08 Nov 1997",
    phone: "+91 98912 44567",
    doctor: "Dr. Vikram Rao",
    department: "Neurology",
    clinicName: "Neurology Wing, Floor 2",
    date: "2026-05-11",
    time: "10:00",
    duration: 30,
    status: "Pending",
    type: "New Patient",
    intakeComplete: false,
    insuranceVerified: true,
    insuranceProvider: "Niva Bupa Health",
  },
  {
    id: "A004",
    patientId: "P008",
    patientName: "Priya Sharma",
    patientAvatar: "PS",
    dob: "14 Jun 2000",
    phone: "+91 98567 88901",
    doctor: "Dr. Arjun Nair",
    department: "Internal Medicine",
    clinicName: "General Medicine OPD",
    date: "2026-05-11",
    time: "11:00",
    duration: 30,
    status: "Completed",
    type: "Follow-up",
    intakeComplete: true,
    insuranceVerified: true,
    insuranceProvider: "HDFC ERGO Health",
  },
  {
    id: "A005",
    patientId: "P005",
    patientName: "Karan Singh",
    patientAvatar: "KS",
    dob: "03 Sep 1972",
    phone: "+91 99881 55678",
    doctor: "Dr. Sneha Iyer",
    department: "Cardiology",
    clinicName: "Cardiac Centre, Floor 3",
    date: "2026-05-11",
    time: "11:30",
    duration: 45,
    status: "No-Show",
    type: "Routine Check",
    intakeComplete: true,
    insuranceVerified: true,
    insuranceProvider: "New India Assurance",
  },
  {
    id: "A006",
    patientId: "P010",
    patientName: "Meera Iyer",
    patientAvatar: "MI",
    dob: "27 Feb 1984",
    phone: "+91 98789 10123",
    doctor: "Dr. Priya Sharma",
    department: "Endocrinology",
    clinicName: "Diabetes & Endocrine Clinic",
    date: "2026-05-11",
    time: "14:00",
    duration: 30,
    status: "Confirmed",
    type: "Follow-up",
    intakeComplete: true,
    insuranceVerified: true,
    insuranceProvider: "United India Insurance",
  },
  {
    id: "A007",
    patientId: "P016",
    patientName: "Lakshmi Naidu",
    patientAvatar: "LN",
    dob: "10 Apr 1960",
    phone: "+91 98456 76789",
    doctor: "Dr. Vikram Rao",
    department: "Neurology",
    clinicName: "Neurology Wing, Floor 2",
    date: "2026-05-11",
    time: "14:30",
    duration: 60,
    status: "Confirmed",
    type: "Emergency",
    notes: "Stroke patient — high priority, requires neuro escort",
    intakeComplete: false,
    insuranceVerified: false,
    insuranceProvider: "Star Health Insurance",
  },
  {
    id: "A008",
    patientId: "P011",
    patientName: "Rahul Bose",
    patientAvatar: "RB",
    dob: "19 Dec 1990",
    phone: "+91 99567 21234",
    doctor: "Dr. Vikram Rao",
    department: "Orthopedics",
    clinicName: "Bone & Joint Clinic, Floor 1",
    date: "2026-05-11",
    time: "15:00",
    duration: 30,
    status: "Pending",
    type: "Consultation",
    intakeComplete: false,
    insuranceVerified: true,
    insuranceProvider: "Niva Bupa Health",
  },
  {
    id: "A009",
    patientId: "P002",
    patientName: "Sanya Kapoor",
    patientAvatar: "SK",
    dob: "05 Jul 1993",
    phone: "+91 99301 22345",
    doctor: "Dr. Arjun Nair",
    department: "Pulmonology",
    clinicName: "Respiratory Medicine, Floor 1",
    date: "2026-05-12",
    time: "09:00",
    duration: 30,
    status: "Confirmed",
    type: "Follow-up",
    intakeComplete: true,
    insuranceVerified: true,
    insuranceProvider: "HDFC ERGO Health",
  },
  {
    id: "A010",
    patientId: "P007",
    patientName: "Vikram Nair",
    patientAvatar: "VN",
    dob: "28 Aug 1978",
    phone: "+91 99123 77890",
    doctor: "Dr. Meera Pillai",
    department: "Nephrology",
    clinicName: "Dialysis & Renal Centre",
    date: "2026-05-12",
    time: "10:00",
    duration: 45,
    status: "Confirmed",
    type: "Dialysis Review",
    intakeComplete: true,
    insuranceVerified: false,
    insuranceProvider: "Star Health Insurance",
  },
  {
    id: "A011",
    patientId: "P014",
    patientName: "Kavitha Rajan",
    patientAvatar: "KR",
    dob: "17 Oct 1981",
    phone: "+91 98234 54567",
    doctor: "Dr. Sneha Iyer",
    department: "Rheumatology",
    clinicName: "Arthritis & Rheumatology Clinic",
    date: "2026-05-12",
    time: "11:00",
    duration: 30,
    status: "Pending",
    type: "Follow-up",
    intakeComplete: false,
    insuranceVerified: true,
    insuranceProvider: "ICICI Lombard Health",
  },
  {
    id: "A012",
    patientId: "P020",
    patientName: "Sunita Agarwal",
    patientAvatar: "SA",
    dob: "01 May 1971",
    phone: "+91 98789 10234",
    doctor: "Dr. Priya Sharma",
    department: "Endocrinology",
    clinicName: "Diabetes & Endocrine Clinic",
    date: "2026-05-13",
    time: "09:30",
    duration: 30,
    status: "Confirmed",
    type: "Insulin Review",
    intakeComplete: true,
    insuranceVerified: true,
    insuranceProvider: "United India Insurance",
  },
];

export const departmentStats: DepartmentStat[] = [
  { name: "Cardiology", patients: 87, color: "var(--accent-blue)" },
  { name: "Neurology", patients: 64, color: "var(--accent-purple)" },
  { name: "Pulmonology", patients: 58, color: "var(--accent-cyan)" },
  { name: "Endocrinology", patients: 72, color: "var(--accent-yellow)" },
  { name: "Orthopedics", patients: 49, color: "#38bdf8" },
  { name: "Surgery", patients: 55, color: "#6366f1" },
  { name: "Nephrology", patients: 38, color: "#a78bfa" },
  { name: "Others", patients: 27, color: "#6b7280" },
];
